#!/usr/bin/env bash

# usage:
#  - go to the web page for the puzzle e.g. 0x00
#  - copy the text
#  - ./init 0x00
#
# if you have another template: 
#  init 0x00 tmpl.asm

# sane defaults
set -euox pipefail
IFS=$'\n\t'

# defaults to what i think is the name of the template
readonly name="${1}.asm"
readonly template="${2:-__tmpl__.asm}"

function main() {
  cp "${template}" "${name}"
  xclip -out >> "${name}"
}; main
